apiVersion: apps/v1
kind: Deployment
metadata:
  name: art-gallery
  labels:
    app: art-gallery
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: art-gallery
  template:
    metadata:
      labels:
        app: art-gallery
    spec:
      containers:
      - name: nodejs-gui
        image: acresion/art-gallery:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1Gi        
        ports:
        - containerPort: 3000
        env:
        - name: GALLERY_USERNAME
        valueFrom:
          secretKeyRef:
            name: art-gallery-secret
            key: username
        - name: GALLERY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: art-gallery-secret
            key: password
        - name: GALLERY_URI
        valueFrom:
          secretKeyRef:
            name: art-gallery-secret
            key: uri
