apiVersion: v1
kind: Service
metadata:
 name: art-gallery-service
spec:
  type: NodePort
  ports:
  - port: 3010
    targetPort: 3010
  selector:
    app: art-gallery-gui


#try different ports, maybe try starting a shell in the0 pod, and use curl
#tomorrow quota: check the container to see if there is a route internally
#then find a way to expose the image to the browser
#also figure out a way to install mongodb in here