name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t acresion/art-gallery:latest
    - name: push the image
      run: |
        docker login -u acresion -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push acresion/art-gallery:latest
    
      
  
